name = "jobmejob"
main = "jobmejob-worker.js"
compatibility_date = "2026-01-18"
workers_dev = true
preview_urls = false

routes = [
  { pattern = "api.jobmejob.com", zone_name = "jobmejob.com", custom_domain = true }
]

[triggers]
crons = ["0 */4 * * *"]
